/**
 * Puma Prey APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RefreshToken { 
    token?: string;
    expires?: Date;
    created?: Date;
    createdByIp?: string;
    revoked?: Date;
    revokedByIp?: string;
    replacedByToken?: string;
    reasonRevoked?: string;
    readonly isExpired?: boolean;
    readonly isRevoked?: boolean;
    readonly isActive?: boolean;
}