/**
 * Puma Prey APIs
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RefreshToken } from './refreshToken';

export interface User { 
    memberId?: number;
    email?: string;
    phoneNumber?: string;
    creditCardNumber?: string;
    creditCardExpiration?: string;
    billingAddress1?: string;
    billingAddress2?: string;
    billingCity?: string;
    billingState?: string;
    billingZip?: string;
    safariIds?: Array<number>;
    refreshTokens?: Array<RefreshToken>;
}