name: angular build

on:
  pull_request:
    branches: [main]
    paths:
      - "src/Squirrel/**"
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/Squirrel
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: setup Node 22.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: src/Squirrel/package-lock.json

      - name: npm install
        run: npm ci --legacy-peer-deps

      - name: ng build
        run: npx ng build
