name: Puma Scan Professional

on:
  workflow_dispatch:

permissions:
  id-token: write # write jwt token
  actions: read # read gh actions
  contents: read # read access to the repo
  security-events: write # write access to advanced security

jobs:
  run:
    name: scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: run puma scan
        uses: pumasecurity/puma-scan-pro-action@v1.6.0
        env:
          PUMA_LICENSE: ${{ secrets.PUMA_LICENSE }}
        with:
          project-paths: "./src/Coyote/Coyote.csproj"
          output-formats: "json,html,sarif"
          output-file: "./security-analysis/puma-scan"
          settings-paths: "./.pumafile"
          threshold-high: "0"

      - name: Publish Puma Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: PumaScan
          path: "./security-analysis/*"

      - name: Publish SARIF Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./security-analysis/puma-scan.sarif
          category: "security"
